version: "3.9"

services:
  node-server:
    build: ./node-app
    container_name: node-server
    ports:
      - "3000:3000"
    depends_on:
      - python-socket
    networks:
      - app-net

  python-socket:
    build: ./python-app
    container_name: python-socket
    ports:
      - "5000:5000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
